// Run in the fixture browser with: await window.runAuthoringChecks().
window.runAuthoringChecks = async () => {
    const results=[];
    const tick=()=>new Promise(r=>setTimeout(r,35));
    const assert=(ok,message)=>{if(!ok)throw new Error(message); results.push(message);};
    const text=()=>document.getElementById('app').innerText;
    const button=(label)=>Array.from(document.querySelectorAll('button')).find(b=>b.textContent.trim()===label);
    const click=async label=>{const b=button(label); if(!b)throw new Error(`Missing button: ${label}`); b.click(); await tick();};
    const input=async(el,value)=>{Object.getOwnPropertyDescriptor(el.tagName==='SELECT'?HTMLSelectElement.prototype:HTMLInputElement.prototype,'value').set.call(el,value); el.dispatchEvent(new Event(el.tagName==='SELECT'?'change':'input',{bubbles:true})); await tick();};
    const field=(label)=>Array.from(document.querySelectorAll('.field')).find(f=>f.querySelector('label')?.textContent===label);
    window.mount(); await tick();
    await click('Next'); assert(text().includes('Name is required.'),'inline basics validation');
    await input(document.getElementById('sn-recipe'),'stopped'); await click('Next');
    assert(text().includes('Channel state settings'),'recipe enters condition');
    assert(!field('Enabled').querySelector('input').checked,'recipes start disabled');
    await input(field('Minimum duration (seconds)').querySelector('input'),'-1'); await click('Next');
    assert(text().includes('must be at least 0'),'condition bounds checked before advance');
    await input(field('Minimum duration (seconds)').querySelector('input'),'300'); await click('Next');
    assert(text().includes('including stopped and undeployed'),'state-specific eligibility copy');
    await click('Single channel'); await click('Next'); assert(text().includes('Select a scope target.'),'scope prerequisite validation');
    const scope=field('Scope').querySelector('select'); await input(scope,'c'); await click('Next');
    assert(text().includes('Configured scope: Channel: ADT'),'review resolves configured label');
    await click('Quick edit'); assert(document.getElementById('sn-monitor-name').value==='Production channel stopped for 5 minutes','quick edit shares recipe draft');
    await click('Wizard'); assert(text().includes('Review Production channel stopped'),'wizard restores same step and draft');
    control.calls=[]; const test=button('Test'); test.click(); test.click(); await tick();
    assert(control.calls.length===1,'same-tick double test sends once');
    assert(button('Back to list').disabled && document.querySelector('fieldset').disabled,'test locks navigation and draft');
    control.pending.shift().reject(new Error('offline')); await tick();
    assert(text().includes('Your draft is preserved.'),'failed draft test preserves edits with inline error');
    assert(document.getElementById('sn-monitor-name').value==='Production channel stopped for 5 minutes','failed test keeps entered name');
    await click('Test'); control.pending.shift().resolve({ok:true,outcomes:[{channelId:'c',channelName:'ADT',status:'INSUFFICIENT_DATA',valueSummary:'Warming up'}]}); await tick();
    assert(control.modal.sections[0].text.includes('INSUFFICIENT_DATA'),'unknown test remains unknown');
    control.permission=false; const before=control.calls.length; await click('Create monitor'); assert(control.calls.length===before,'action-time permission revocation prevents create'); control.permission=true;
    control.allowLeave=false; await click('Cancel'); assert(!control.closed,'dirty cancel preserves editor');
    assert(await window.mayLeaveAuthoring()===false,'Sentinel navigation guard retains dirty draft');
    control.allowLeave=true; await click('Cancel'); assert(control.closed,'explicit discard closes editor');
    window.mount('copy'); await tick(); await click('Quick edit');
    assert(document.getElementById('sn-monitor-name').value==='Saved (copy)','copy seeds new name');
    assert(!button('Delete') && !text().includes('Alerting history'),'copy has no delete or saved history');
    assert(field('Suppressed by').querySelector('select').value==='10','copied dependency explicit');
    control.calls=[]; button('Create monitor').click(); button('Create monitor').click(); await tick();
    assert(control.calls.length===1 && control.calls[0].payload.id===undefined && control.calls[0].payload.enabled===false,'copy creates once without original identity and remains disabled');
    control.pending.shift().reject(new Error('forbidden')); await tick(); assert(text().includes('Save failed'),'write rejection preserves draft');
    window.mount('edit'); await tick(); await click('Wizard'); assert(!button('4. Review & Test').disabled,'existing edits permit all step navigation');
    await click('4. Review & Test'); assert(text().includes('Dependency: Parent'),'review names dependency');
    await click('1. Basics'); await input(document.getElementById('sn-monitor-name'),'Retained draft');
    window.mount('resume'); await tick(); assert(document.getElementById('sn-monitor-name').value==='Retained draft','host unmount restores browser-session draft');
    control.allowLeave=true; await click('Cancel'); assert(control.retainedDraft===null,'explicit discard clears retained draft');
    window.mount('schedule-copy'); await tick(); assert(!button('Delete') && button('Create window'),'schedule copy cannot update or delete original');
    assert(field('Name').querySelector('input').value==='Saved schedule (copy)','schedule copy seeds name');
    control.calls=[]; await click('Create window');
    assert(control.calls[0].payload.id===undefined && control.calls[0].payload.enabled===false && control.calls[0].payload.timezone==='America/New_York','schedule copy preserves zone and recurrence without identity');
    control.pending.shift().reject(new Error('offline')); await tick(); assert(text().includes('Save failed'),'schedule failure retains draft');
    return {passed:results.length,results,overflow:document.documentElement.scrollWidth>innerWidth};
};
