CREATE TABLE sentinel_monitor (
    id                        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                      VARCHAR2(255) NOT NULL UNIQUE,
    description               VARCHAR2(1024),
    monitor_type              VARCHAR2(32) NOT NULL,
    scope_type                VARCHAR2(16) NOT NULL,
    scope_id                  CHAR(36),
    enabled                   NUMBER(1) DEFAULT 1 NOT NULL,
    severity                  VARCHAR2(16) NOT NULL DEFAULT 'WARNING',
    config_json               CLOB NOT NULL,
    min_consecutive_breaches  NUMBER NOT NULL DEFAULT 1,
    suppressed_by_monitor_id  NUMBER REFERENCES sentinel_monitor(id) ON DELETE SET NULL,
    created_by                NUMBER,
    created_time              TIMESTAMP NOT NULL,
    updated_by                NUMBER,
    updated_time              TIMESTAMP
)

CREATE INDEX idx_sentinel_monitor_scope ON sentinel_monitor (scope_type, scope_id)

CREATE INDEX idx_sentinel_monitor_enabled ON sentinel_monitor (enabled)

CREATE TABLE sentinel_alert_event (
    id                  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    monitor_id          NUMBER NOT NULL REFERENCES sentinel_monitor(id) ON DELETE CASCADE,
    channel_id          CHAR(36) NOT NULL,
    metadata_id         NUMBER,
    severity            VARCHAR2(16) NOT NULL,
    status              VARCHAR2(16) NOT NULL,
    message             VARCHAR2(1024) NOT NULL,
    opened_time         TIMESTAMP NOT NULL,
    resolved_time       TIMESTAMP,
    acknowledged_by     NUMBER,
    acknowledged_time   TIMESTAMP,
    ack_comment         VARCHAR2(1024),
    details_json        CLOB,
    suppressed          NUMBER(1) DEFAULT 0 NOT NULL
)

CREATE INDEX idx_sentinel_alert_event_monitor_channel ON sentinel_alert_event (monitor_id, channel_id)

CREATE INDEX idx_sentinel_alert_event_status ON sentinel_alert_event (status)

CREATE INDEX idx_sentinel_alert_event_opened ON sentinel_alert_event (opened_time)

CREATE TABLE sentinel_trigger_state (
    id                          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    monitor_id                  NUMBER NOT NULL REFERENCES sentinel_monitor(id) ON DELETE CASCADE,
    channel_id                  CHAR(36) NOT NULL,
    metadata_id                 NUMBER,
    state                       VARCHAR2(20) NOT NULL DEFAULT 'INSUFFICIENT_DATA',
    consecutive_breach_count    NUMBER NOT NULL DEFAULT 0,
    last_value_json             CLOB,
    open_alert_event_id         NUMBER,
    last_change_time            TIMESTAMP,
    last_evaluated_time         TIMESTAMP,
    CONSTRAINT uq_sentinel_trigger_state UNIQUE (monitor_id, channel_id, metadata_id)
)

CREATE INDEX idx_sentinel_trigger_state_monitor ON sentinel_trigger_state (monitor_id)

ALTER TABLE sentinel_trigger_state
    ADD CONSTRAINT fk_sentinel_trigger_state_alert_event
    FOREIGN KEY (open_alert_event_id) REFERENCES sentinel_alert_event(id) ON DELETE SET NULL

CREATE TABLE sentinel_channel_activity_sample (
    id               NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    channel_id       CHAR(36) NOT NULL,
    sample_time      TIMESTAMP NOT NULL,
    received_delta   NUMBER NOT NULL DEFAULT 0,
    sent_delta       NUMBER NOT NULL DEFAULT 0,
    error_delta      NUMBER NOT NULL DEFAULT 0,
    filtered_delta   NUMBER NOT NULL DEFAULT 0,
    queued_snapshot  NUMBER NOT NULL DEFAULT 0
)

CREATE INDEX idx_sentinel_activity_sample_channel_time ON sentinel_channel_activity_sample (channel_id, sample_time)

CREATE TABLE sentinel_channel_activity_trend (
    id             NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    channel_id     CHAR(36) NOT NULL,
    hour_bucket    TIMESTAMP NOT NULL,
    received_sum   NUMBER NOT NULL DEFAULT 0,
    sent_sum       NUMBER NOT NULL DEFAULT 0,
    error_sum      NUMBER NOT NULL DEFAULT 0,
    avg_queued     DOUBLE PRECISION NOT NULL DEFAULT 0,
    min_queued     NUMBER NOT NULL DEFAULT 0,
    max_queued     NUMBER NOT NULL DEFAULT 0,
    CONSTRAINT uq_sentinel_activity_trend UNIQUE (channel_id, hour_bucket)
)

CREATE INDEX idx_sentinel_activity_trend_channel_hour ON sentinel_channel_activity_trend (channel_id, hour_bucket)

CREATE TABLE sentinel_connector_status_event (
    id               NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    channel_id       CHAR(36) NOT NULL,
    metadata_id      NUMBER NOT NULL,
    previous_state   VARCHAR2(24),
    new_state        VARCHAR2(24) NOT NULL,
    changed_time     TIMESTAMP NOT NULL
)

CREATE INDEX idx_sentinel_connector_status_event_channel ON sentinel_connector_status_event (channel_id, metadata_id, changed_time)

CREATE TABLE sentinel_action (
    id                        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                      VARCHAR2(255) NOT NULL UNIQUE,
    description               VARCHAR2(1024),
    enabled                   NUMBER(1) DEFAULT 1 NOT NULL,
    action_type               VARCHAR2(16) NOT NULL,
    condition_json            CLOB NOT NULL,
    operation_mode            VARCHAR2(16) NOT NULL DEFAULT 'ON_PROBLEM',
    repeat_interval_seconds   NUMBER,
    max_repeats               NUMBER,
    config_json               CLOB NOT NULL,
    created_by                NUMBER,
    created_time              TIMESTAMP NOT NULL,
    updated_by                NUMBER,
    updated_time              TIMESTAMP
)

CREATE INDEX idx_sentinel_action_enabled ON sentinel_action (enabled)

CREATE TABLE sentinel_action_dispatch_log (
    id               NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alert_event_id   NUMBER NOT NULL REFERENCES sentinel_alert_event(id) ON DELETE CASCADE,
    action_id        NUMBER REFERENCES sentinel_action(id) ON DELETE SET NULL,
    dispatch_time    TIMESTAMP NOT NULL,
    success          NUMBER(1) NOT NULL,
    error_message    VARCHAR2(1024)
)

CREATE INDEX idx_sentinel_action_dispatch_log_event ON sentinel_action_dispatch_log (alert_event_id)

CREATE TABLE sentinel_maintenance_window (
    id             NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           VARCHAR2(255) NOT NULL,
    scope_type     VARCHAR2(16) NOT NULL,
    scope_id       CHAR(36),
    active_from    TIMESTAMP NOT NULL,
    active_until   TIMESTAMP NOT NULL,
    enabled        NUMBER(1) DEFAULT 1 NOT NULL,
    created_by     NUMBER,
    created_time   TIMESTAMP NOT NULL
)

CREATE INDEX idx_sentinel_maintenance_window_scope ON sentinel_maintenance_window (scope_type, scope_id)
