import {build} from 'esbuild';import {chromium} from '@playwright/test';import {mkdir,readFile,writeFile} from 'node:fs/promises';import {createServer} from 'node:http';import {fileURLToPath} from 'node:url';import path from 'node:path';import assert from 'node:assert/strict';
const dir=path.dirname(fileURLToPath(import.meta.url)),out=path.resolve(dir,'../../target/coverage-browser');await mkdir(out,{recursive:true});
await build({entryPoints:[path.join(dir,'coverage/entry.jsx')],outfile:path.join(out,'bundle.js'),bundle:true,format:'esm',alias:{'@oie/web-shell':path.join(dir,'coverage/host.jsx'),'@oie/web-ui':path.join(dir,'coverage/host.jsx')}});
const plugin=await readFile(path.join(dir,'../web/plugin.jsx'),'utf8'),css=plugin.match(/const SENTINEL_CSS = `([\s\S]*?)`;/)[1];
await writeFile(path.join(out,'index.html'),`<style>body{font:14px Arial;margin:16px}.dt td,.dt th{padding:8px;text-align:left;border-bottom:1px solid #ccc}.panel{border:1px solid #ccc}.panel-body,.panel-header{padding:12px}.btn{padding:6px}.text-err{color:#a12323}:root{--text-dim:#555;--text-faint:#555}${css}</style><div id="root" class="sn-view"></div><script type="module" src="/bundle.js"></script>`);
const server=createServer(async(req,res)=>{res.setHeader('Content-Type',req.url==='/bundle.js'?'text/javascript':'text/html');res.end(await readFile(path.join(out,req.url==='/bundle.js'?'bundle.js':'index.html')));});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));let browser;
try {
    browser=await chromium.launch({headless:true,...(process.env.COVERAGE_BROWSER?{executablePath:process.env.COVERAGE_BROWSER}:{})});const page=await browser.newPage({viewport:{width:1280,height:800}});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(`http://127.0.0.1:${server.address().port}`);
    await page.getByRole('table',{name:'Channel coverage'}).waitFor();await page.getByText('Latest recorded evaluation: unknown.',{exact:false}).waitFor();
    assert.equal(await page.getByText('Recently evaluated healthy',{exact:false}).count(),0);
    await page.getByRole('button',{name:'Create monitor for this channel'}).first().click();assert.equal(await page.evaluate(()=>window.coverage.intent.kind),'newMonitor');assert.equal(await page.evaluate(()=>window.coverage.intent.channelId),'a');assert.equal(await page.evaluate(()=>window.coverage.posts),0);
    await page.screenshot({path:path.join(out,'desktop.png'),fullPage:true});await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.screenshot({path:path.join(out,'mobile.png'),fullPage:true});
    await page.evaluate(()=>window.coverage.fail=true);await page.getByRole('button',{name:'Refresh',exact:true}).click();await page.getByText('Coverage offline',{exact:false}).waitFor();assert.equal(await page.getByText('Payments',{exact:true}).isVisible(),true);
    await page.evaluate(()=>{window.coverage.fail=false;window.coverage.permission=false;});await page.getByRole('button',{name:'Retry',exact:true}).click();await page.getByRole('button',{name:'Refresh',exact:true}).waitFor();assert.equal(await page.getByRole('button',{name:'Create monitor for this channel'}).count(),0);
    await page.evaluate(()=>{window.coverage.hold=true;});await page.getByRole('button',{name:'Refresh',exact:true}).click();await page.waitForFunction(()=>window.coverage.pending.length===1);await page.evaluate(()=>window.coverage.tick());await page.waitForFunction(()=>window.coverage.pending.length===2);
    await page.evaluate(()=>window.coverage.pending[1]({...window.coverage.response,rows:[{channelId:'new',channelName:'Newest snapshot',status:'NO_COVERAGE',monitors:[]}]}));await page.getByText('Newest snapshot',{exact:true}).waitFor();await page.evaluate(()=>window.coverage.pending[0](window.coverage.response));assert.equal(await page.getByText('Payments',{exact:true}).count(),0);
    await page.evaluate(()=>{window.coverage.hold=false;window.coverage.response={...window.coverage.response,rows:[]};});await page.getByRole('button',{name:'Refresh',exact:true}).click();await page.getByText('No visible channels in the current inventory.').waitFor();
    await page.evaluate(()=>window.coverage.response.inventoryStatus='UNKNOWN');await page.getByRole('button',{name:'Refresh',exact:true}).click();await page.getByText('Coverage inventory unavailable',{exact:false}).waitFor();
    assert.deepEqual(errors,[]);console.log('PASS: unknown vs healthy, visible evaluation time, create-monitor intent only, read failure retention, permission, stale ordering, empty/failed inventory, 390px layout');
}finally{if(browser)await browser.close();await new Promise(resolve=>server.close(resolve));}
