// Controlled real React fixture; database responses simulated, no live engine.
import { build } from 'esbuild';
import { mkdtemp, readFile, writeFile, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { createServer } from 'node:http';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import assert from 'node:assert/strict';
const base=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');const playwright=await import(process.env.SENTINEL_PLAYWRIGHT_PACKAGE||'playwright');
const dir=await mkdtemp(path.join(tmpdir(),'sentinel-health-'));let browser,server;
try {
 const fixture=`import React from '${base}/node_modules/react/index.js';import{createRoot}from'${base}/node_modules/react-dom/client.js';import{ClusterHealth}from'${base}/web/pages/health.jsx';window.requests=[];const root=createRoot(document.getElementById('root'));let generation=0;window.remount=()=>root.render(React.createElement(ClusterHealth,{key:++generation}));window.remount();`;
 await build({stdin:{contents:fixture,loader:'jsx',resolveDir:base},outfile:path.join(dir,'fixture.js'),bundle:true,format:'iife',plugins:[{name:'fixture',setup(b){
 b.onResolve({filter:/^@oie\//},args=>({path:args.path,namespace:'fixture'}));b.onResolve({filter:/^\.\.\/(api.js|ui.jsx)$/},args=>args.importer.endsWith('health.jsx')?({path:args.path,namespace:'fixture'}):undefined);
 b.onLoad({filter:/.*/,namespace:'fixture'},args=>({loader:'js',resolveDir:base,contents:args.path==='@oie/web-shell'?`import React from '${base}/node_modules/react/index.js';export const platform={React};`:args.path==='../ui.jsx'?`export const fmtTime=v=>v;`:`export const errText=e=>e.message;export const getClusterHealth=()=>new Promise((resolve,reject)=>window.requests.push({resolve,reject}));`}));
 }}]});
 await writeFile(path.join(dir,'index.html'),'<!doctype html><meta name="viewport" content="width=device-width"><style>body{font:14px Arial;line-height:1.5;margin:16px;color:#253443}button{font:inherit;padding:8px}table{border-collapse:collapse;width:100%}td,th{padding:8px;text-align:left}button:focus-visible{outline:2px solid #125ca5;outline-offset:2px}</style><div id="root"></div><script src="/fixture.js"></script>');
 server=createServer(async(req,res)=>{res.setHeader('Content-Type',req.url.endsWith('.js')?'text/javascript':'text/html');res.end(await readFile(path.join(dir,req.url==='/fixture.js'?'fixture.js':'index.html')));});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));browser=await playwright.chromium.launch({headless:true});const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(`http://127.0.0.1:${server.address().port}`);
 const observed=data=>({state:'OBSERVED',data});const unknown={state:'UNKNOWN',data:null,detail:'Read unavailable; no health conclusion can be drawn.'};
 const sample={leader:observed({state:'LIVE',nodeId:'leader-a',epoch:3,observedAt:'2026-10-06T12:00:00Z',expiresAt:'2026-10-06T12:01:00Z'}),nodes:observed(['leader-a','standby-b']),jobs:observed([{job_name:'collector',node_id:'leader-a',lease_epoch:3,outcome:'SUCCESS',started_time:'2026-10-06T11:59:45Z',finished_time:'2026-10-06T11:59:50Z',last_success_time:'2026-10-06T11:59:50Z',last_success_node:'leader-a',last_success_epoch:3}]),storage:observed({pending:1,oldestPendingEdge:'2026-10-06T11:55:00Z',samples:2,trends:3,events:4}),retention:observed({collectorIntervalSeconds:30,evaluatorIntervalSeconds:60,sampleRetentionDays:2,trendRetentionDays:3,resolvedAlertRetentionDays:4}),estimates:observed({visibleDeployedChannels:1,rawSampleRows:5760,hourlyTrendRows:72,assumption:'Estimated rows; physical database bytes unknown.'})};
 const reply=async(index,value)=>page.evaluate(({index,value})=>window.requests[index].resolve(value),{index,value});
 await page.waitForFunction(()=>window.requests.length===1);await reply(0,sample);await page.getByText('Recent success observed',{exact:true}).waitFor();assert.equal(await page.getByText('No shared observation',{exact:true}).count(),3);assert.match(await page.locator('body').innerText(),/oldest pending edge age 300 seconds/);assert.match(await page.locator('body').innerText(),/standby-b/);
 const refresh=page.getByRole('button',{name:'Refresh health',exact:true});await refresh.click();await page.waitForFunction(()=>window.requests.length===2);await page.evaluate(()=>window.requests[1].reject(new Error('permission lost')));await page.getByRole('alert').waitFor();assert.match(await page.getByRole('alert').innerText(),/timestamps have not advanced/);
 await refresh.click();await page.waitForFunction(()=>window.requests.length===3);await reply(2,{...sample,leader:observed({...sample.leader.data,nodeId:'leader-b',epoch:4}),nodes:unknown});await page.getByText('No success recorded for current leader epoch',{exact:true}).waitFor();assert.match(await page.locator('body').innerText(),/nodes: Unknown/);
 await refresh.click();await page.waitForFunction(()=>window.requests.length===4);await page.evaluate(()=>window.remount());await page.waitForFunction(()=>window.requests.length===5);await reply(4,{...sample,leader:observed({...sample.leader.data,state:'EXPIRED'}),jobs:unknown});await reply(3,sample);await page.waitForTimeout(20);assert.match(await page.locator('body').innerText(),/Lease: EXPIRED/);assert.equal(await page.getByText('Recent success observed',{exact:true}).count(),0);assert.match(await page.locator('body').innerText(),/jobs: Unknown/);
 await refresh.click();await page.waitForFunction(()=>window.requests.length===6);await reply(5,{...sample,jobs:observed([null])});await page.getByRole('alert').waitFor();assert.match(await page.getByRole('alert').innerText(),/Invalid health observations/);
 await refresh.click();await page.waitForFunction(()=>window.requests.length===7);await reply(6,{...sample,jobs:observed([{...sample.jobs.data[0],outcome:'ERROR'}])});await page.getByText('Last tick reported errors',{exact:true}).waitFor();assert.match(await page.locator('body').innerText(),/2026-10-06T11:59:50Z/);
 await refresh.click();await page.waitForFunction(()=>window.requests.length===8);await reply(7,{...sample,jobs:observed([{...sample.jobs.data[0],last_success_time:'2026-10-06T11:00:00Z'}])});await page.getByText('Success observation stale',{exact:true}).waitFor();
 await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await refresh.focus();assert.equal(await refresh.evaluate(node=>node===document.activeElement),true);assert.deepEqual(errors,[]);
 console.log('PASS: shared leader/standby evidence, missing jobs unknown, authorized pending age, current-vs-prior epoch, independent section failure, permission refresh retains timestamp, stale unmounted response ignored, malformed rows, failed/old success, keyboard, 390px overflow, zero page errors. No live engine.');
}finally{if(browser)await browser.close();if(server)await new Promise(resolve=>server.close(resolve));await rm(dir,{recursive:true,force:true});}
