import {build} from 'esbuild';import {chromium} from '@playwright/test';import {mkdir,readFile,writeFile} from 'node:fs/promises';import {createServer} from 'node:http';import {fileURLToPath} from 'node:url';import path from 'node:path';import assert from 'node:assert/strict';
const dir=path.dirname(fileURLToPath(import.meta.url)),out=path.resolve(dir,'../../target/incident-notes-browser');await mkdir(out,{recursive:true});await build({entryPoints:[path.join(dir,'incident-notes/entry.jsx')],outfile:path.join(out,'bundle.js'),bundle:true,format:'esm',alias:{'@oie/web-shell':path.join(dir,'incident-notes/host.jsx'),'@oie/web-ui':path.join(dir,'incident-notes/host.jsx')}});
const source=await readFile(path.join(dir,'../web/plugin.jsx'),'utf8'),css=source.match(/const SENTINEL_CSS = `([\s\S]*?)`;/)[1];await writeFile(path.join(out,'index.html'),`<style>body{font:14px Arial;margin:16px}.panel{border:1px solid #ccc}.panel-body{padding:12px}.panel-header{padding:12px;font-weight:bold}.btn{padding:6px}:root{--text-faint:#555;--text-dim:#555;--bg3:#eee;--warn:#775500;--err:#a12323}${css}</style><div id="root" class="sn-view"></div><script type="module" src="/bundle.js"></script>`);
const server=createServer(async(req,res)=>{res.setHeader('Content-Type',req.url==='/bundle.js'?'text/javascript':'text/html');res.end(await readFile(path.join(out,req.url==='/bundle.js'?'bundle.js':'index.html')));});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));let browser;
try{browser=await chromium.launch({headless:true,...(process.env.INCIDENT_NOTES_BROWSER?{executablePath:process.env.INCIDENT_NOTES_BROWSER}:{})});const page=await browser.newPage({viewport:{width:1280,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(`http://127.0.0.1:${server.address().port}`);await page.getByText('Destination timeout').waitFor();
 // Pending mutation locks synchronously, and labelled controls work by keyboard.
 await page.getByLabel('Handoff note', {exact:true}).fill('<script>alert(1)</script>\nRepair destination');await page.evaluate(()=>window.incident.holdWrite=true);const append=page.getByRole('button',{name:'Append note',exact:true});await append.focus();await page.keyboard.press('Enter');await page.waitForFunction(()=>window.incident.pending.length===1);assert.equal(await page.getByLabel('Handoff note',{exact:true}).isDisabled(),true);assert.equal(await page.getByRole('button',{name:'Appending note…'}).isDisabled(),true);assert.equal(await page.evaluate(()=>window.incident.writes.length),1);
 // Malformed response leaves immutable retry payload; server committed original request.
 await page.evaluate(()=>{const body=window.incident.writes[0].body;window.incident.notes=[{id:body.requestId,eventId:42,actorId:7,createdTime:'2026-10-06T11:01:00Z',text:body.text}];window.incident.holdWrite=false;window.incident.pending[0]({});});await page.getByRole('button',{name:'Retry same note'}).waitFor();await page.getByRole('button',{name:'Retry same note'}).click();await page.getByText(/Last confirmed note:/).waitFor();assert.deepEqual(await page.evaluate(()=>window.incident.writes[0].body),await page.evaluate(()=>window.incident.writes[1].body));assert.equal(await page.evaluate(()=>window.incident.notes.length),1);assert.equal(await page.locator('script:not([type="module"])').count(),0);
 await page.getByText('<script>alert(1)</script>\nRepair destination',{exact:true}).waitFor();await page.getByText('Nearby incidents on this channel',{exact:false}).click();await page.screenshot({path:path.join(out,'desktop.png'),fullPage:true});await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.screenshot({path:path.join(out,'mobile.png'),fullPage:true});
 // Cursor paging appends older notes and pauses automatic replacement until refresh.
 await page.evaluate(()=>window.incident.older=[{id:'00000000-0000-0000-0000-000000000077',eventId:42,actorId:8,createdTime:'2026-10-06T10:50:00Z',text:'Earlier shift note'}]);await page.getByRole('button',{name:'Refresh timeline',exact:true}).click();await page.getByRole('button',{name:'Load older notes'}).click();await page.getByText('Earlier shift note',{exact:true}).waitFor();assert.equal(await page.getByRole('button',{name:'Load older notes'}).count(),0);
 // Independent persistent read error retains prior evidence and successful receipt.
 await page.evaluate(()=>window.incident.failRead=true);await page.getByRole('button',{name:'Refresh timeline',exact:true}).click();await page.getByText(/Refresh failed: Injected inventory/).waitFor();assert.equal(await page.getByText('Destination timeout').count(),1);await page.evaluate(()=>window.incident.failRead=false);await page.getByRole('button',{name:'Refresh timeline',exact:true}).click();await page.waitForFunction(()=>!document.body.textContent.includes('Refresh failed:'));
 // Action-time revoked permission blocks write even before React re-render.
 await page.getByLabel('Handoff note',{exact:true}).fill('Second note');const before=await page.evaluate(()=>window.incident.writes.length);await page.evaluate(()=>window.incident.allowed=false);await page.getByRole('button',{name:'Append note',exact:true}).click();assert.equal(await page.evaluate(()=>window.incident.writes.length),before);await page.evaluate(()=>window.renderIncident());await page.waitForFunction(()=>document.body.textContent.includes('permission is required'));assert.equal(await page.getByLabel('Handoff note',{exact:true}).isDisabled(),true);
 // Old unmounted read cannot populate a new incident panel.
 await page.evaluate(()=>{window.incident.holdRead=true;window.renderIncident(43);});await page.waitForFunction(()=>window.incident.readPending.length===1);await page.evaluate(()=>{window.incident.holdRead=false;window.renderIncident(42);});await page.getByText('Destination timeout').waitFor();await page.evaluate(()=>window.incident.readPending[0]({event:{id:43}}));assert.equal(await page.getByText(/Timeline response could not/).count(),0);
 assert.deepEqual(errors,[]);console.log('PASS: keyboard append, synchronous lock, uncertain replay, immutable payload, escaped text, stale read evidence, revoked permission, unmount ordering, desktop/390px');
}finally{if(browser)await browser.close();await new Promise(resolve=>server.close(resolve));}
