import {build} from 'esbuild';import {chromium} from '@playwright/test';import {mkdir,readFile,writeFile} from 'node:fs/promises';import {createServer} from 'node:http';import {fileURLToPath} from 'node:url';import path from 'node:path';import assert from 'node:assert/strict';
const dir=path.dirname(fileURLToPath(import.meta.url)),out=path.resolve(dir,'../../target/saved-views-browser');await mkdir(out,{recursive:true});await build({entryPoints:[path.join(dir,'saved-views/entry.jsx')],outfile:path.join(out,'bundle.js'),bundle:true,format:'esm',alias:{'@oie/web-shell':path.join(dir,'saved-views/host.jsx'),'@oie/web-ui':path.join(dir,'saved-views/host.jsx')}});
const source=await readFile(path.join(dir,'../web/plugin.jsx'),'utf8'),css=source.match(/const SENTINEL_CSS = `([\s\S]*?)`;/)[1];await writeFile(path.join(out,'index.html'),`<style>body{font:14px Arial;margin:16px}.panel{border:1px solid #ccc}.panel-body{padding:12px}.btn{padding:6px}.sn-filterbar select,.sn-filterbar input{max-width:220px}:root{--text-faint:#555;--text-dim:#555;--bg3:#eee;--warn:#775500;--err:#a12323}${css}</style><div id="root" class="sn-view"></div><script type="module" src="/bundle.js"></script>`);
const server=createServer(async(req,res)=>{res.setHeader('Content-Type',req.url==='/bundle.js'?'text/javascript':'text/html');res.end(await readFile(path.join(out,req.url==='/bundle.js'?'bundle.js':'index.html')));});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));let browser;
try{browser=await chromium.launch({headless:true,...(process.env.SAVED_VIEWS_BROWSER?{executablePath:process.env.SAVED_VIEWS_BROWSER}:{})});const page=await browser.newPage({viewport:{width:1280,height:800}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
    const visit=()=>page.goto(`http://127.0.0.1:${server.address().port}`);await visit();await page.getByLabel('Triage view name').waitFor();
    await page.getByPlaceholder('Search message…').fill('Error');await page.getByLabel('Problems page size').selectOption('100');await page.waitForFunction(()=>window.saved.queries.at(-1)?.pageSize===100 && window.saved.queries.at(-1)?.q==='Error');
    await page.getByLabel('Triage view name').fill('Shift handoff');await page.getByRole('button',{name:'Save current view'}).click();await page.getByRole('button',{name:'Replace saved view'}).waitFor();
    const persisted=await page.evaluate(()=>JSON.parse(localStorage.getItem('sentinel:triage-views:v1:engine-a:7')));assert.equal(persisted.views[0].filters.q,'Error');assert.equal(persisted.views[0].pageSize,100);assert.equal(JSON.stringify(persisted).includes('event'),false);
    await page.getByPlaceholder('Search message…').fill('Other');await page.getByRole('button',{name:'Load view',exact:true}).click();assert.equal(await page.getByPlaceholder('Search message…').inputValue(),'Error');
    await page.screenshot({path:path.join(out,'desktop.png'),fullPage:true});await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.screenshot({path:path.join(out,'mobile.png'),fullPage:true});
    // Remount restores the first query, including server sort and page size.
    await page.evaluate(()=>{const key='sentinel:triage-views:v1:engine-a:7',data=JSON.parse(localStorage.getItem(key));data.last.sort={column:'severity',dir:'ASC'};localStorage.setItem(key,JSON.stringify(data));});
    await visit();await page.waitForFunction(()=>window.saved.queries.length>0);assert.equal(await page.evaluate(()=>window.saved.queries[0].q),'Error');assert.equal(await page.evaluate(()=>window.saved.queries[0].pageSize),100);assert.equal(await page.evaluate(()=>window.saved.queries[0].sort),'severity');assert.equal(await page.evaluate(()=>window.saved.queries[0].sortDir),'ASC');
    // Account switch never reads the preceding account's view, and resets page params.
    await page.evaluate(()=>window.switchSavedUser(8));await page.waitForFunction(()=>window.saved.queries.at(-1)?.pageSize===25);assert.equal(await page.getByPlaceholder('Search message…').inputValue(),'');assert.equal(await page.locator('select[aria-label="Saved triage view"] option').count(),1);
    await page.evaluate(()=>window.switchSavedUser(7));await page.waitForFunction(()=>window.saved.queries.at(-1)?.pageSize===100);await page.getByLabel('Saved triage view').selectOption('Shift handoff');
    // Loading a saved view invalidates an outstanding request during debounce.
    await page.evaluate(()=>window.saved.hold=true);await page.getByRole('button',{name:'Refresh',exact:true}).click();await page.waitForFunction(()=>window.saved.pending.length===1);
    await page.getByPlaceholder('Search message…').fill('Different');await page.getByRole('button',{name:'Load view',exact:true}).click();await page.evaluate(()=>{window.saved.hold=false;window.saved.pending[0]({items:[{id:99,message:'STALE SAVED VIEW'}],total:1});});await page.waitForFunction(()=>window.saved.queries.at(-1)?.q==='Error');assert.equal(await page.getByText('STALE SAVED VIEW').count(),0);
    await page.getByRole('button',{name:'Delete selected view'}).click();assert.equal(await page.locator('select[aria-label="Saved triage view"] option').count(),1);
    // Corrupt data cannot be applied; a local reset leaves Problems working.
    await page.evaluate(()=>{localStorage.setItem('sentinel:triage-views:v1:engine-a:7','{');window.dispatchEvent(new StorageEvent('storage',{key:'sentinel:triage-views:v1:engine-a:7'}));});await page.getByRole('button',{name:'Reset local saved views'}).click();assert.equal(await page.locator('select[aria-label="Saved triage view"] option').count(),1);
    // Context outage has an explicit operation-only fallback with no anonymous writes.
    await page.evaluate(()=>{window.saved.contextFail=true;window.switchSavedUser(8);});await page.getByRole('button',{name:'Use Problems without saved views'}).click();assert.equal(await page.getByRole('button',{name:'Save current view'}).isDisabled(),true);assert.equal(await page.getByLabel('Problems page size').isEnabled(),true);
    assert.deepEqual(errors,[]);console.log('PASS: save/replace/load/delete, restored first query, page size, user isolation, stale ordering, corruption reset, context-failure fallback, 390px');
}finally{if(browser)await browser.close();await new Promise(resolve=>server.close(resolve));}
